# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:

      mention_user:
        description: 'User:'
        required: true
        type: choice
        options:
          - ''
          - 'Alberto - U01U29TKUAC'
          - 'GabyTaboada - U01U29TKUAC'
          - 'gaetan.pauchet - U01U29TKUAC'
          - 'Melisa Kindelan - U01U29TKUAC'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Generate Slack ID
        run: |
          echo "OLOLO=$(${{ github.event.inputs.mention_user }} | rev | cut -c 1-11 | rev)" >> >> $GITHUB_ENV
          echo ${{ github.event.inputs.mention_user }} | rev | cut -c 1-11 | rev 

      - name: Generate Slack ID
        run: |
          echo $OLOLO
